# Generated by Django 3.0.7 on 2021-08-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('todo', 'Todo'), ('done', 'DOne')], default='todo', max_length=10),
        ),
    ]
